version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo Installing kubectl...
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/
      - kubectl version --client

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - # Remplacez eu-west-1 si votre cluster est ailleurs
      - AWS_REG=eu-west-1
      - REPO_URL=723951822917.dkr.ecr.eu-west-1.amazonaws.com/mon-app-repo
      - aws ecr get-login-password --region $AWS_REG | docker login --username AWS --password-stdin $REPO_URL
      - IMAGE_TAG=latest

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - # Assurez-vous que votre Dockerfile est à la racine
      - docker build -t $REPO_URL:$IMAGE_TAG .

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPO_URL:$IMAGE_TAG
      - echo Updating Kubeconfig for EKS...
      - aws eks update-kubeconfig --name devops-low-cost --region eu-west-1
      - echo Deploying to Kubernetes cluster...
      - # On applique le fichier qui contient le Deployment et le Service
      - kubectl apply -f k8s/deployment.yaml
      - echo Restarting deployment to pick up new image...
      - kubectl rollout restart deployment/mon-app-deployment
      - echo Deployment successful!
