name: Build and Deploy to AWS EKS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Mise à jour vers v4 (supprime l'alerte Node 20)
      - name: Checkout Source Code
        uses: actions/checkout@v4

      # 2. Mise à jour vers v4 (supprime l'alerte Node 20)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      # 3. Mise à jour vers v2 (supprime l'alerte 'set-output' et masque le mot de passe)
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # 4. Build et Push
      - name: Build, Tag, and Push Image to ECR
        env:
          # Ici, on récupère le registre via la nouvelle méthode compatible v2
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: mon-app-repo
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      # 5. Mise à jour config Kubernetes
      - name: Update Kubeconfig
        run: |
          aws eks update-kubeconfig --name devops-low-cost --region eu-west-1

      # 6. Déploiement final
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl rollout restart deployment/mon-app
